[package]
name = "hestix-api"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web framework
axum = "0.8.4"

# Async runtime
tokio = { version = "1.46.1", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# UUIDs, useful for tokens or IDs
uuid = { version = "1.17.0", features = ["v4"] }

# Logging / debugging
tracing = "0.1"
tracing-subscriber = "0.3"

# Optional: dotenv support for env files
dotenvy = "0.15"

# DB sync
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "macros"] }