name: CI and Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Offline build & tests
  build-offline:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: "true"
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --locked --all-features
      - run: cargo test --locked --all-features

  # Docker build
  docker:
    needs: [build-offline]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: t1me0n/hestix-core-api
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=t1me0n/hestix-core-api:buildcache
          cache-to: type=registry,ref=t1me0n/hestix-core-api:buildcache,mode=max
